---
title: "Ribosome accumulation during early phase resistance training"
author: Daniel Hammarström^1,2,£^&ast;,Sjur Øfsteng^2,£^  Bent R. Rønnestad^2^, Stian Ellefsen^1,3^
date: ""
header-includes:
  - \usepackage{wasysym}
csl: resources/experimental-physiology.csl
bibliography: resources/bibliography.bib
output:
  word_document:
    reference_docx: resources/manuscript_word_template.docx
editor_options: 
  chunk_output_type: console
---
<!-- This is a comment  -->
<!-- Add comments after each reference for tracking (eg[@RN2364]<!-- comment -->
<!-- After references, add a row break without space (this will put the reference on the end on the line). -->

<!-- The formatting of the manuscript is based on faseb journal, find csl-files at https://github.com/citation-style-language/styles -->

<!-- Figure texts are included in the end of the manuscript file -->
<!-- Tables in a separate file -->

```{r, include = FALSE}

source("./R/libs.R")
# Settings for chunk options
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


^1^ Section for Health and Exercise Physiology, Department of Public Health and Sport Sciences, Inland Norway University of Applied Sciences, Lillehammer, Norway. 

^2^ Swedish School of Sport and Health Sciences, Stockholm, Sweden.

^3^ Innlandet Hospital Trust, Lillehammer, Norway. </div>

^£^ These authors contributed equally to this work




<div custom-style="correspondence_style">
&ast; Correspondance

Daniel Hammarström, Section for Health and Exercise Physiology, Department of Public Health and Sport Sciences, Inland Norway University of Applied Sciences, Lillehammer, Norway. Email: daniel.hammarstrom@inn.no  </div>



<div custom-style="runningtitle_style">**Running title:** Ribosome biogenesis in early phase resistace training</div>


\pagebreak


# Abstract
<div custom-style="abstract_style">
<!-- Word limit 200 -->
Abstract...


**Keywords:** Resistance training, ribosome biogenesis


</div>

\pagebreak

# Introduction

Our skeletal muscles not only constitutes our locomotive apparatus but also serve as our primary storage site of amino acids. This makes the musculoskeletal system a critical target for interventions that promotes health across the lifespan [@RN763]. The beneficial effects of resistance-training (RT) are in large part mediated through exercise-induced changes in the balance between muscular protein breakdown and synthesis, with successful RT leading to net protein accretion and muscle hypertrophy. A traditional view of exercise-induced muscle hypertrophy has been that muscle protein accumulates as a consequence of repeated episodes of elevated post-exercise protein synthesis in the acute phase, resulting in a net-positive protein balance over time. Indeed, one bout of resistance exercise acutely up-regulates skeletal muscle protein synthesis up to 48-hr after exercise [@RN786] and subsequently, repeated bouts would lead to accumulation of muscle protein over time [@RN1272; @RN1642]. 
In recent years, this view has been supplemented with evidence showing that chronic RT also leads to an increased resting synthetic rate of muscle protein [@RN1521; @RN1866; @RN1897]. An increase in the resting protein synthetic rate has been postulated to be related to an increased translational capacity, i.e. accumulation of ribosomes [@RN1897; @RN1912], a notion supported by observations relating exercise-induced changes in total RNA, a proxy marker for ribosome abundance, to muscle hypertrophy [@RN1644, @RN1755]. Furthermore, in vitro studies shows that direct inhibition of ribosomal RNA (rRNA) transcription or inhibition of up-stream transcription factors leading to halted biosynthesis of ribosomes results in diminished cellular growth [@RN1755; @RN1754; @RN884].  Formation of new ribosomes is a complex and energy demanding process involving the whole transcriptional apparatus [@RN1920, @RN1820].  In skeletal muscle, a single bout of resistance exercise elevates markers of ribosome biogenesis in skeletal muscle evident from both Figueiredo et al. and Nader et al. who evaluated immature forms of rRNA in response to exercise in the untrained state [@RN1644; @RN1037]. Studies’ examining repeated bouts of resistance exercise suggests that RT leads to accumulation of ribosomes. Bickel et al. showed that two subsequent bouts of a hypertrophic stimulus increased total RNA at 72 h after a second bout of RT [@RN1520]. Following three weeks of RT, Brook et al. reported an increase in total RNA with no further increase after three additional weeks of training [@RN1642]. The findings of Brook et al. fits with observations from our laboratory where we saw a ~30% increase in total RNA per tissue weight after two weeks of RT. Following an additional 10 weeks of RT the RNA content tended to normalized without reaching baseline values (Hammarström et al. 2017 unpublished observation). These data suggests that ribosome accumulation per tissue weight, reaches a plateau in the early phase of RT. Interestingly, in the study by Figueiredo and colleagues, acute exercise in the trained state (after eight weeks of RT), rRNA and pre-rRNA rapidly decreases in response to acute exercise [@RN1644]. 
Based on these observations we are hypothesizing that (1) ribosome accumulation occurs in the early phase (3-4 weeks) of RT and (2) reaches a plateau during this phase in response to constant volume RT and finally (3) that fluctuations in ribosome abundance occurs in response to altered training volume and training cessation. Subsequently the aim of this study is to characterize fluctuations in ribosomal biogenesis during the initial phase of RT, in response to altered training volumes and in response to a short-term de-training period.

# Methods

## Study overview

## Muscle strength and thickness
Muscle strength was assessed as maximal knee extension isokinetic (90&deg; sec<sup>-1</sup>) and isometric (60&deg; angle, fully extended leg 0&deg;) torque. After a brief warm-up (5-min cycling, RPE 12-14), participants were seated and secured in the individually adjusted dynamometer. The test protocol consisted of unilateral knee-extensions. Participants were instructed to gradually increase their effort during three warm-up repetitions (50, 60 and, 70% of subjective maximal effort). After a 30-sec restitution period participants were instructed to perform three repetitions with maximal effort in the concentric phase. Sixty seconds after the isokinetic test the lever automatically moved to a 60&deg; angle and participants were instructed to push against the lever enough to see feedback from the visual feedback system. After an additional 15-sec restitution period, participants were instructed to push against the lever with maximal effort. During the same assessment session, participants remained seated in the dynamometer for meassurement from both legs. The first measurement was alternated between legs and sessions. For statistical treatment of the data, all successful attempts were used. Successful attempts were decided based on participants (...). The last strength assessment at baseline was performed at least **seven** days prior to the first biopsy sampling. At least one strength was performed on separate days with two sessions allowed perform on the same day with a short rest between sessions. Post training assessments were performed approximately 48 hours after the last session and after seven days of no training.

Muscle thickness was assessed using (...) ultra sound. 


## Muscle biopsy sampling 
Muscle specimens were sampled bilaterally from *m. vastus laterlis* under local anesthesia (lidocaion %, Manufacturer, Oslo, Norway) using a disposable needle (12-14 gauge, Universal plus, Medax, Italy), operated with a spring loaded device (Bard Magnum). Two to four passes were made to get sufficient material. One to two aliquots of the samples were quickly dissected free from connective and fat tissue, weighed and frozen in isopentan chilled to -80&deg;C and stored at -80&deg;C until further processing. At baseline, after twelve weeks of training and, after the de-training period, a further aliquot from each sample was selected for immunohistochemistry analysis and subsequently immersed in 4% formalin for fixation.        


## RNA and protein extraction
Frozen muscle tissue was homogenized in 1 ml of Trizol (ThermoFisher Scientific, Oslo, Norway) spiked with 0.04 ng of an external, non-mammalian, RNA spike-in (Lambda, Takara Bioscience). Mechanical disruption of the samples was achieved using Zirconium Oxide Beads (0.5 mm, Next Advance, Inc., New York, USA) and a bead mill (Bullet blender, Next Advance). Chloroform (200 &#956;l) was added prior to centrifugation (12000 g, 15 min at 4&deg;C) to achieve phase separation. Four houndred fifty &#956;l of the upper aqueous phase was transferred to a fresh tube and 500 &#956;l of isopropanol was added to precipitate the RNA. After a 10 min incubation at room temperature, samples were centrifuged (12000 g, 10 min at 4&deg;C), after which a pellet formed. The pellet was washed three times in chilled 75% ethanol with centrifugation between each wash (7500 g, 5 min at 4&deg;C). After the final wash all ethanol was removed and the pellet was eluted in 0.1X Tris-EDTA buffer. RNA concentration and purity was assessed by spectrophotometry. All samples had 260/280 ratios > 1.95.

Protein was extracted from Trizol preparations according to manufacturers instructions and [@KOPEC] with modifications. The remaining aqueous phase was removed and DNA was precipitated by the addition of XXX &#956;l of absolute ethanol followed by gentle centrifugation (2000 g, 5 min at room temperature). An aliquot of the phenol-ethanol phase, corresponding to ~1.75 mg of tissue, was transferred to to a fresh tube. After addition of at least two volumes of isopropanol and incubation (10 min at room temperature), samples were centrifuged (7500 g, 10 min 4&deg;C) and a pellet formed. The pellet was washed three times in 95% ethanol with each wash separated by centrifugation (5000g, 5 min at room temperature). After the last wash all liquid was removed and 45 &#956;l of Kopec buffer was added (4% SDS, 300 mM Tris ..., pH; containing protease and phosphatase inhibitors). Pellets were incubated at 50&deg;C for three hours after which the majority of samples were dissolved. Any undissolved material was sedimented by centrifugation (10000 g, 10 min at room temperature). Protein concentrations were measured (Pierce Detergent Compatible Bradford Assay, ThermoFisher Scientific). Sample were normalized in 4X Laemmli buffer (Bio-Rad Norway AS, Oslo, Norway), boiled (95&deg;C, 5 min) and stored at -20&deg;C before later use.

## Quantitative polymerase chain reaction (qPCR)
Complementary DNA (cDNA) was synthesized in technical duplicates from 500 ng of total RNA using random hexemer and anchored Oligo-dT primers (Thermo Scientific) together with Superscript IV (ThermoFisher Scientific) according to manufacturer's instruction. qPCR reactions were performed with diluted cDNA (2 &#956;l, 1:25 dilution), a SYBR-green based commercial master mix (PowerUp™ SYBR™ Green Master Mix, Thermo Fisher) and, target-specific primers (500 nM) in 10 &#956;l reaction volumes using a real-time detection system (QuantStudio 5 Real-Time PCR System, Thermo Fisher). Fast cycling was used (1 sec denaturing, 30 sec annealing) after UNG (2 min, 50&deg;C) and polymerase  (2 min, 95&deg;C) activation. Melt curves were collected from all reactions to confirm single product amplification. Primers were further evaluated by agarose gel electrophoresis an non-template control experiments. Primer sequences and their respective average performances are shown in Table 2.

Raw fluorescence data was exported from the QuantStudio software and estimates of quantification cycles (Cq) and amplification efficiencies were derived using the qpcR package[qpcR-package]. Relative abundance data was linearized using average efficiencies per primer pair and reaction specific Cq-values before any further statistical treatment.

## Immunoblotting
Protein samples (20 &#956;g) were separated on 4-20% Tris-Glycin gels (Criterion TGX Precast Gels, Bio-Rad) at 250 V for 45 min using the recommended running buffer (25 mM Tris, 192 mM Glycin, 0.1% SDS). All samples from the same participant were run on the same gel and all samples were run in at leat duplicates. Separated samples were transferred to &#956m PVDF membranes (Immun-Blot, Bio-Rad) using wet transfer (25 mM Tris, 192 Glycin, 10% vol/vol methanol) at a constant voltage of 300 mA for 3 h. Membranes were then stained to confirm transfer and enable total protein quantification using a reversible protein stain (Pierce Reversible Protein Stain, ThermoFisher Scientiﬁc). Primary antibodies were acquired to detect UBF (F-9, sc-13125, Santa-Cruz Biotechnology) and ribosomal protein S6 (54D2, #2317, Cell signaling technology). After blocking (Tris-buffered saline blocking buffer, 20 mM Tris, 150 mM NaCl, 5% fat-free milk, 0.1% Tween-20), membranes were incubated over-night with primary antibodies diluted in blocking buffer (UBF, 1:200; S6, 1:1000) followed by incubation with a secondary antibody conjugated to horseradish peroxidase (Anti-mouse IgG, #7076, Cell Singlaing Technology, 1:10000). Membranes were washed 6 &#215; 5 min after incubation with primary antibodies and 8 &#215; 5 min after incubation with the secondary antibody. All incubation and washing steps were performed at 4&deg;C using an automatic membrane processor (BlotCycler, Precision Biosystems, Mansﬁeld, MA, USA). Chemiluminescent signals from membranes were detected after 5 min incubation in substrate (Super Signal West Femto Maximum Sensitivity Substrate, ThermoFisher Scientiﬁc) using a documentation system (). Total protein content was quantified whole membrane images defined as the mean gray value of the whole lane. Between-lane gray values were used as background subtracted from protein values. Total protein quantification was done using ImageJ [REF]. Chemiluminescence signals were quantified using Image Studio Lite (LI-COR Biotechnology, Lincoln, NE, USA).

## Immunohistochemistry

## Statistics and data analysis


# Results

# Discussion

# References
<div id="refs"></div>



