---
title: "Tables"
output:
  word_document:
    reference_docx: resources/tables_manuscript_word_template.docx
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

source("./R/libs.R")
library(flextable); library(officer)

```



```{r table1-characteristics}

# Read dxa data

dxa_whole <- read_excel("./data/tr010_dxa_standarddefinitions.xlsx") %>%
  dplyr::select(Etternavn, Kjønn,Målingsdato,Alder, Vekt:`HeleVev%fett`) %>%
  pivot_longer(names_to = "variable", values_to = "value", cols = Vekt:`HeleVev%fett`) %>%
  mutate(value = gsub("kg", "", value), 
         value = gsub("[[:space:]]", "", value, fixed = FALSE), 
         value = as.numeric(value)) %>%

  separate(Etternavn, into = c("Study", "participant")) %>%
  dplyr::select(participant, Date = Målingsdato, variable, value) %>%
  filter(!(participant %in% c("P08", "P20", "P17"))) %>%
  group_by(participant) %>%
  mutate(time = if_else(Date == min(Date), "S0", 
                        if_else(Date == max(Date), "post1w", 
                                "S12")), 
         leg = if_else(variable == "BeinhøyreMagermasse", "R", "L")) %>%
  filter(variable %in% c("HeleBeinmasse", 
                         "HeleFettmasse", 
                         "HeleVevmasse", 
                         "HeleMagermasse" ,
                         "Vekt", 
                         "HeleTotalmasse")) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  mutate(fat_rel = 100*(HeleFettmasse/HeleTotalmasse)) %>%
  dplyr::select(participant, time, Vekt,HeleTotalmasse, fat_rel) %>%
  filter(time == "S0") 

# DXA weight stature

read_excel("./data/tr010_age_participant.xlsx") %>%
  inner_join(dxa_whole) %>%
  mutate(age = difftime(recruited, dob)/365.2425, 
         bmi = weight/(height/100)^2) %>%
  dplyr::select(participant, group, height, weight,age, sex,bmi, fat_rel) %>%

  group_by(group, sex) %>%
  summarise(n = n(), 
            Age = mean(age, na.rm = TRUE), 
            age.sd = sd(age, na.rm = TRUE),
            mass = mean(weight), 
            mass.sd = sd(weight),
            stature = mean(height),
            stature.sd = sd(height), 
            BMI = mean(bmi), 
            bmi.sd = sd(bmi), 
            relfat = mean(fat_rel), 
            relfat.sd = mean(fat_rel) ) %>%
  ungroup() %>%
  mutate(n = as.character(n), 
         age = paste0(sprintf("%.1f", round(Age, 1)), " (", sprintf("%.1f", round(age.sd, 1)), ")"),
         mass = paste0(sprintf("%.1f", round(mass, 1)), " (", sprintf("%.1f", round(mass.sd, 1)), ")"),
         stature = paste0(sprintf("%.1f", round(stature, 1)), " (", sprintf("%.1f", round(stature.sd, 1)), ")"),
         BMI = paste0(sprintf("%.1f", round(BMI, 1)), " (", sprintf("%.1f", round(bmi.sd, 1)), ")"),
         fat = paste0(sprintf("%.1f", round(relfat, 1)), " (", sprintf("%.1f", round(relfat.sd, 1)), ")"))%>%
  dplyr::select(group, sex, n, age, mass, stature, BMI, fat) %>%
  pivot_longer(names_to = "variable", values_to = "values", n:fat) %>%
  pivot_wider(names_from = c(sex,group), values_from = values) %>%
  
  mutate(variable =  factor(variable,
                          levels = c("n", "age", "mass", "stature", "BMI", "fat"), 
                          labels = c("n", "Age (yrs)", "Body mass, (kg)", "Stature (cm)", "Body mass index (kg/m<sup>2</sup>)", "Body fat (%)"))) %>%
  
  dplyr::select(variable, F_experiment, M_experiment, F_control, M_control) %>%
  flextable() %>% 
  italic(i = ~variable == "n", j = 1, italic = TRUE) %>%
  compose(part = "body", i = 5, j = 1,
         value = as_paragraph("Body mass index (kg m",
                              as_sup("-2"), ")")) %>%
  
  set_header_labels(variable = "",
    F_experiment = "Female", M_experiment = "Male",
    F_control = "Female", M_control = "Male") %>%
  
  
   add_header_row(values = c("", "Experimental group", "Experimental group", "Control group", "Control group"), top = TRUE) %>%
  merge_at(i = 1, j = 2:3, part = "header") %>%
  merge_at(i = 1, j = 4:5, part = "header") %>%
  align(align = "center", part = "header") %>%
    fontsize(size = 8, part = "body") %>%
    fontsize(size = 10, part = "header") %>%
  add_header_lines(values = "Table 1. Participant characteristics.") %>%
  autofit()



```



\pagebreak


```{r table-2-primers}

# Read qpcr data
qdat <- readRDS("./data/derivedData/qpcr/qpcr_compiled.RDS")

primer_performance <- qdat %>%
  group_by(target) %>%
  summarise(mean.cq = mean(cq, na.rm = TRUE), 
            sd.cq = sd(cq, na.rm = TRUE), 
            mean.eff = mean(eff)) 


merge_custom <- function(ft, x, columns){
  z <- rle(x)
  rows_at <- cumsum(z$lengths) - z$lengths + 1

  for(i in seq_along(rows_at)){
    for(j in columns)
      ft <- merge_at(x = ft, i = seq( rows_at[i], rows_at[i] + z$lengths[i] - 1), j = j)
  }

  ft
}

# Read primer data 
primer_table <- read_excel("./data/tr010_primers.xlsx", sheet = 1) %>%
  dplyr::select(target = primer_id, forward, reverse, full_name, symbol_ext) %>%
  inner_join(primer_performance) %>%
  mutate(performance = paste0(sprintf("%.1f", round(mean.cq,1)), " (", sprintf("%.1f",        round(sd.cq,1)), "), E = ", sprintf("%.2f", round(mean.eff,2))), 
         forward = paste0("F: 5'-", forward, "-3'"), 
         reverse = paste0("R: 3'-", reverse, "-5'")) %>% 
  
  
  
  dplyr::select(symbol_ext, full_name, forward, reverse, performance) %>%
  pivot_longer(names_to = "primer", values_to = "seq", forward:reverse) %>%
dplyr::select(Symbol = symbol_ext, 'Transcript name' = full_name, Sequence = seq, 'Mean Cq (SD) and efficiency' = performance) 

primer_table %>%
  flextable() %>%
  merge_custom(x = primer_table$Symbol, columns = c(1, 2, 4)) %>%
  add_header_lines(values = "Table 2. Primer sequences and average performance.") %>%
      fontsize(size = 8, part = "body") %>%
    fontsize(size = 10, part = "header") %>%
  autofit()



```


\pagebreak

```{r table3-regression-models-muscle-thickness}
# Save model 

comb.m1 <- readRDS("./data/derivedData/ubf-tot-rna-model/comb_m1.RDS")

comb.m1 <- summary(comb.m1)


reg_results <- 
  cbind(rbind(comb.m1$fixed,
      comb.m1$random$participant, 
      comb.m1$random$`participant:leg`, 
      comb.m1$spec_pars), 
      data.frame(coef = c("Intercept", 
                          "UBF protein levels (SD-units)", 
                          "Session 1-4",
                          "Session 4-8", 
                          "Session 8-12", 
                          "De-training",
                          "Between Participant variation",
                          "Between Participant:Leg variation", 
                          "Residual SD"))) %>%
  remove_rownames() %>%
  dplyr::select(coef, Estimate, Est.Error, lwr = `l-95% CI`, upr = `u-95% CI`)


std_border = fp_border(color="gray")

reg_results %>%
  
  mutate(Estimate = round(Estimate, 2), 
         Est.Error = round(Est.Error, 2), 
         lwr = round(lwr, 2), 
         upr = round(upr, 2)) %>%
  
  flextable() %>%
  set_header_labels(coef = "Coefficient", 
                    Est.Error = "SD", 
                    lwr = "Lower 95% CI", 
                    upr = "Upper 95% CI") %>%
    add_header_lines(values = "Table 3. Effect of UBF levels, sessions and de-training on RNA-levels.") %>%
  
 # bold(i = c(5, 6, 13, 14, 20, 21), j = c(2:6), bold = TRUE) %>%
  
 # hline(i = c(9, 17), part="body", border = std_border ) %>%
      fontsize(size = 8, part = "body") %>%
    fontsize(size = 10, part = "header") %>%
      fontsize(size = 7, part = "footer") %>%
  
  footnote( i = 2, j = 2,
            value = as_paragraph(
              c("The dependent variable is total RNA levels (log)")
            ),
            ref_symbols = c("a"),
            part = "header", inline = TRUE) %>%
    footnote( i = c(3, 4, 5), j = 1,
            value = as_paragraph(
              c("Slope in response to session 1-4", 
                "Change in slope in session 4-8", 
                "Change in slope in session 8-12")
            ),
            ref_symbols = c("b","c","d"),
            part = "body", inline = TRUE) %>%
  
  autofit()
  




```




\pagebreak


```{r table4-regression-models-muscle-thickness}
# Save model 



hyp.pre.m3 <- readRDS( "./data/derivedData/ubf-tot-rna-model/hyp_pre_m3.RDS")




m3.sum <- summary(hyp.pre.m3)

# combine output from all models 



reg_results <- 
  cbind(rbind(m3.sum$fixed,
      m3.sum$random$participant, 
      m3.sum$random$`participant:leg`, 
      m3.sum$spec_pars), 
      data.frame(coef = c("Intercept", 
                          "Sex (Male)", 
                          "Mean Total RNA",
                          "Mean Total RNA increase per session", 
                          "Between Participant variation", 
                          "Between Participant:Leg variation", 
                          "Residual SD"))) %>%
  remove_rownames() %>%
  dplyr::select(coef, Estimate, Est.Error, lwr = `l-95% CI`, upr = `u-95% CI`)


std_border = fp_border(color="gray")

reg_results %>%
  
  mutate(Estimate = round(Estimate, 2), 
         Est.Error = round(Est.Error, 2), 
         lwr = round(lwr, 2), 
         upr = round(upr, 2)) %>%
  
  flextable() %>%
  set_header_labels(coef = "Coefficient", 
                    Est.Error = "SD", 
                    lwr = "Lower 95% CI", 
                    upr = "Upper 95% CI") %>%
    add_header_lines(values = "Table 4. Total RNA as a predictor of muscle growth.") %>%
  
 # bold(i = c(5, 6, 13, 14, 20, 21), j = c(2:6), bold = TRUE) %>%
  
 # hline(i = c(9, 17), part="body", border = std_border ) %>%
      fontsize(size = 8, part = "body") %>%
    fontsize(size = 10, part = "header") %>%
  
  footnote( i = 2, j = 2,
            value = as_paragraph(
              c("The dependent variable is \U0394 Muscle thickness (mm)")
            ),
            ref_symbols = c("a"),
            part = "header") %>%
  
  autofit()
  



```


